Repository GodotVR/godot_openxr, pull requests merged in 2021-12, with the labels that each got.

#137 Create the passthrough layer on demand
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.cpp
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.h
Labels: bug, Oculus, android

#140 Automatically start the passthrough layer at construction
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.cpp
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.h
Labels: enhancement, Oculus, android

#142 Add methods to keep track of the passthrough state
  src/gdclasses/OpenXRConfig.cpp
  src/gdclasses/OpenXRConfig.h
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.cpp
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.h
Labels: enhancement

#146 Hand tracking needs to be cleaned up on session destroy
  src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.cpp
  src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.h
Labels: bug
