Repository GodotVR/godot_openxr, pull requests merged in 2021-10, with the labels that each got.

#102 Add support for touch detection on A/X and B/Y buttons.
  src/openxr/OpenXRApi.cpp
  src/openxr/OpenXRApi.h
Labels: enhancement

#103 Copy the `addons/godot-openxr/config/` directory into the `assets` folder when building the aar binary
  android/build.gradle
  android/src/main/assets/.gitignore
  android/src/main/java/org/godotengine/plugin/vr/openxr/OpenXRPlugin.kt
Labels: enhancement, android

#104 Set the amplitude parameter when setting the haptic feedback struct
  src/openxr/actions/action.cpp
Labels: bug

#106 Include algorithm
  src/openxr/OpenXRApi.cpp
Labels: bug
