Repository GodotVR/godot_openxr, pull requests merged in 2022-03, with the labels that each got.

#177 Changed info about supported platforms and added shields
  README.md
  demo/addons/godot-openxr/README.md
  openxr_screenshot.jpg
Labels: documentation

#181 Cleanup some message spam, moved some to debug
  src/ARVRInterface.cpp
  src/openxr/OpenXRApi.cpp
  src/openxr/actions/action.cpp
  src/openxr/actions/actionset.cpp
  src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.cpp
  src/openxr/extensions/xr_ext_performance_settings_extension_wrapper.cpp
  src/openxr/extensions/xr_fb_passthrough_extension_wrapper.cpp
Labels: enhancement

#192 Update Godot Android library dependency
  android/src/main/AndroidManifest.xml
  config.gradle
Labels: android

#141 Make passthrough a toggle on first person controller
  demo/Main.gd
  demo/Main.tscn
  demo/addons/godot-openxr/scenes/first_person_controller_vr.gd
  demo/scenes/Screen.gd
  demo/scenes/Screen.tscn
Labels: enhancement

#193 Fix invalid pose data when controllers are becoming inactive
  android/src/main/AndroidManifest.xml
  config.gradle
  demo/Main.gd
  demo/Main.tscn
  demo/addons/godot-openxr/CHANGES.md
  demo/assets/quest2_controller_models/nextControllerBoth_color1k.png
  demo/assets/quest2_controller_models/nextControllerBoth_color1k.png.import
  demo/assets/quest2_controller_models/shellquest2ControllerMAT.material
  demo/scenes/left_quest2_controller.tscn
  demo/scenes/right_quest2_contoller.tscn
  src/openxr/OpenXRApi.cpp
Labels: bug

#197 Add support for the hand tracking aim state extension
  android/src/main/AndroidManifest.xml
  config.gradle
  demo/Main.tscn
  demo/addons/godot-openxr/CHANGES.md
  demo/scenes/AimPointer.tscn
  src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.cpp
  src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.h
  src/openxr/include/util.h
Labels: enhancement, Oculus
