Repository GodotVR/godot_openxr, pull requests merged in 2022-01, with the labels that each got.

#153 Add interaction profile for the HP Reverb G2 controllers
  demo/addons/godot-openxr/CHANGES.md
  src/openxr/OpenXRApi.cpp
Labels: enhancement

#160 Remove deprecated meta-data tag
  android/src/main/AndroidManifest.xml
  android_samples/demo/src/main/AndroidManifest.xml
  demo/addons/godot-openxr/CHANGES.md
Labels: enhancement, Oculus, android

#161 Update the README to match the update to the documentation
  README.md
  demo/addons/godot-openxr/CHANGES.md
Labels: documentation

#152 Add API for accessing tracking confidence
  demo/ControllerInfo.gd
  demo/ControllerInfo.tscn
  demo/Main.tscn
  demo/addons/godot-openxr/CHANGES.md
  src/gdclasses/OpenXRConfig.cpp
  src/gdclasses/OpenXRConfig.h
  src/gdclasses/OpenXRHand.cpp
  src/gdclasses/OpenXRPose.cpp
  src/gdclasses/OpenXRPose.h
  src/gdclasses/OpenXRSkeleton.cpp
  src/openxr/OpenXRApi.cpp
  src/openxr/OpenXRApi.h
  src/openxr/actions/action.cpp
  src/openxr/actions/action.h
Labels: enhancement

#156 Advance predictive timing on tracked items used *next* frame
  demo/Main.tscn
  demo/addons/godot-openxr/CHANGES.md
  src/openxr/OpenXRApi.cpp
  src/openxr/OpenXRApi.h
  src/openxr/actions/action.cpp
  src/openxr/extensions/xr_ext_hand_tracking_extension_wrapper.cpp
Labels: enhancement
